# Generated by Django 5.2.13 on 2026-05-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("galeries", "0008_collection_cache_mis_a_jour_le_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("entreprise", models.CharField(blank=True, max_length=200)),
                ("adresse", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes internes du photographe"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Référence unique de la commande (ex: CMD-2024-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Titre de la commande (ex: Mariage Sarah & Thomas)",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "message_client",
                    models.TextField(
                        blank=True, help_text="Message personnalisé pour le client"
                    ),
                ),
                (
                    "code_acces",
                    models.CharField(
                        help_text="Code d'accès généré automatiquement",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_preparation", "En préparation"),
                            ("livree", "Livrée"),
                            ("expiree", "Expirée"),
                        ],
                        default="en_preparation",
                        max_length=20,
                    ),
                ),
                (
                    "expire_le",
                    models.DateTimeField(
                        help_text="Date d'expiration de l'accès client"
                    ),
                ),
                (
                    "autoriser_telechargement_web",
                    models.BooleanField(
                        default=True,
                        help_text="Permettre le téléchargement des versions web",
                    ),
                ),
                (
                    "autoriser_telechargement_hd",
                    models.BooleanField(
                        default=False,
                        help_text="Permettre le téléchargement haute résolution",
                    ),
                ),
                ("nombre_vues", models.PositiveIntegerField(default=0)),
                ("premiere_visite_le", models.DateTimeField(blank=True, null=True)),
                ("derniere_visite_le", models.DateTimeField(blank=True, null=True)),
                ("nombre_telechargements", models.PositiveIntegerField(default=0)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="commandes.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PhotoCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre_personnalise",
                    models.CharField(
                        blank=True,
                        help_text="Titre spécifique pour cette commande (optionnel)",
                        max_length=200,
                    ),
                ),
                (
                    "commentaire_interne",
                    models.TextField(
                        blank=True, help_text="Commentaire interne du photographe"
                    ),
                ),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("ajoutee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="commandes.commande",
                    ),
                ),
                (
                    "photo_originale",
                    models.ForeignKey(
                        help_text="Photo du portfolio à inclure dans la commande",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galeries.photo",
                    ),
                ),
                (
                    "version_selectionnee",
                    models.ForeignKey(
                        help_text="Version spécifique à livrer (couleur, monochrome, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galeries.photoversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo de commande",
                "verbose_name_plural": "Photos de commande",
                "ordering": ["ordre_affichage", "ajoutee_le"],
                "unique_together": {
                    ("commande", "photo_originale", "version_selectionnee")
                },
            },
        ),
    ]
