# Generated by Django 5.2.13 on 2026-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccueilConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre_site",
                    models.CharField(
                        default="HORS LES MURS",
                        help_text="Titre principal du site",
                        max_length=100,
                    ),
                ),
                (
                    "sous_titre",
                    models.CharField(
                        default="Studio photographique",
                        help_text="Sous-titre affiché sous le titre principal",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Paysages, architecture, sport, documentaire. Des images capturées hors des sentiers battus, là où la lumière raconte.",
                        help_text="Description principale affichée dans la section hero",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image principale affichée sur la page d'accueil",
                        null=True,
                        upload_to="accueil/hero/",
                    ),
                ),
                (
                    "titre_galeries",
                    models.CharField(
                        default="Galeries",
                        help_text="Titre de la section galeries",
                        max_length=100,
                    ),
                ),
                (
                    "titre_acces_prive",
                    models.CharField(
                        default="Galeries privées",
                        help_text="Titre de la section accès privé",
                        max_length=100,
                    ),
                ),
                (
                    "description_acces_prive",
                    models.TextField(
                        default="Vous avez reçu un code d'accès ? Consultez vos photos personnelles en toute confidentialité.",
                        help_text="Description de la section accès privé",
                    ),
                ),
                (
                    "modal_titre",
                    models.CharField(
                        default="Galerie privée",
                        help_text="Titre du modal d'accès privé",
                        max_length=100,
                    ),
                ),
                (
                    "modal_sous_titre",
                    models.TextField(
                        default="Saisissez le code qui vous a été communiqué pour accéder à vos photos.",
                        help_text="Sous-titre du modal d'accès privé",
                    ),
                ),
                (
                    "modal_placeholder_code",
                    models.CharField(
                        default="ex: HLM-2024-XXX",
                        help_text="Placeholder pour le champ code d'accès",
                        max_length=50,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration de l'accueil",
                "verbose_name_plural": "Configuration de l'accueil",
            },
        ),
        migrations.CreateModel(
            name="SectionAccueil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "contenu",
                    models.TextField(help_text="Contenu de la section (HTML autorisé)"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "Section Hero"),
                            ("galeries", "Avant les galeries"),
                            ("prive", "Avant accès privé"),
                            ("footer", "Avant le footer"),
                        ],
                        help_text="Position de la section sur la page",
                        max_length=20,
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage (plus petit en premier)"
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(
                        default=True, help_text="Afficher cette section"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section d'accueil",
                "verbose_name_plural": "Sections d'accueil",
                "ordering": ["position", "ordre", "titre"],
            },
        ),
    ]
