# Generated by Django 5.2.13 on 2026-05-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Galerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image_couverture",
                    models.ImageField(blank=True, upload_to="galeries/couvertures/"),
                ),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("est_publique", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Galerie",
                "verbose_name_plural": "Galeries",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("date_evenement", models.DateField(blank=True, null=True)),
                ("lieu", models.CharField(blank=True, max_length=200)),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("est_publique", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "galerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="galeries.galerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["galerie", "ordre_affichage", "nom"],
                "unique_together": {("galerie", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_prise", models.DateTimeField(blank=True, null=True)),
                ("appareil", models.CharField(blank=True, max_length=100)),
                ("objectif", models.CharField(blank=True, max_length=100)),
                ("ouverture", models.CharField(blank=True, max_length=10)),
                ("vitesse", models.CharField(blank=True, max_length=20)),
                ("iso", models.PositiveIntegerField(blank=True, null=True)),
                ("largeur_originale", models.PositiveIntegerField()),
                ("hauteur_originale", models.PositiveIntegerField()),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("est_publique", models.BooleanField(default=True)),
                ("est_couverture", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laissez vide pour une photo directe dans la galerie",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="galeries.collection",
                    ),
                ),
                (
                    "galerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="galeries.galerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["ordre_affichage", "titre"],
            },
        ),
        migrations.CreateModel(
            name="PhotoVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "traitement",
                    models.CharField(
                        choices=[
                            ("couleur", "Couleur"),
                            ("monochrome", "Monochrome"),
                            ("sepia", "Sépia"),
                            ("vintage", "Vintage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fichier_web", models.ImageField(upload_to="photos/web/")),
                (
                    "fichier_pleine_resolution",
                    models.ImageField(blank=True, upload_to="photos/hd/"),
                ),
                ("largeur", models.PositiveIntegerField()),
                ("hauteur", models.PositiveIntegerField()),
                ("est_par_defaut", models.BooleanField(default=False)),
                ("est_publique", models.BooleanField(default=True)),
                ("traite_le", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="galeries.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de photo",
                "verbose_name_plural": "Versions de photos",
                "unique_together": {("photo", "traitement")},
            },
        ),
    ]
