# Generated by Django 5.2.13 on 2026-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoOrderingProxy",
            fields=[],
            options={
                "verbose_name": "🔄 Ordre des photos",
                "verbose_name_plural": "🔄 Ordre des photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("galeries.photo",),
        ),
        migrations.CreateModel(
            name="PhotoUploadProxy",
            fields=[],
            options={
                "verbose_name": "📷 Upload de photos",
                "verbose_name_plural": "📷 Upload de photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("galeries.photo",),
        ),
        migrations.AddField(
            model_name="photo",
            name="nom_fichier",
            field=models.CharField(
                blank=True, help_text="Nom du fichier original", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="titre",
            field=models.CharField(
                blank=True, help_text="Titre personnalisé (optionnel)", max_length=200
            ),
        ),
    ]
