# Generated by Django 5.2.13 on 2026-05-12 09:14

from django.db import migrations


def populate_nom_fichier(apps, schema_editor):
    """Populer le champ nom_fichier avec le titre existant ou valeur par défaut"""
    Photo = apps.get_model('galeries', 'Photo')

    for photo in Photo.objects.all():
        if photo.titre:
            # Utiliser le titre existant comme nom de fichier
            photo.nom_fichier = f"{photo.titre}.jpg"
        else:
            # Utiliser un nom par défaut basé sur l'ID
            photo.nom_fichier = f"photo_{photo.id}.jpg"
        photo.save()


def reverse_populate_nom_fichier(apps, schema_editor):
    """Fonction inverse (optionnelle)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0002_add_nom_fichier_to_photo"),
    ]

    operations = [
        migrations.RunPython(populate_nom_fichier, reverse_populate_nom_fichier),
    ]
