# Generated by Django 5.2.13 on 2026-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0003_populate_nom_fichier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affichage_titre_vide",
                    models.CharField(
                        choices=[
                            ("sans_titre", 'Afficher "Sans titre"'),
                            ("vide", "Afficher une chaîne vide"),
                        ],
                        default="sans_titre",
                        help_text="Comment afficher les photos sans titre personnalisé",
                        max_length=20,
                        verbose_name="Affichage des photos sans titre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configuration du site",
            },
        ),
    ]
