# Generated by Django 5.2.13 on 2026-05-12 09:49

from django.db import migrations


def create_default_configuration(apps, schema_editor):
    """Créer l'instance de configuration par défaut"""
    ConfigurationSite = apps.get_model("galeries", "ConfigurationSite")
    ConfigurationSite.objects.get_or_create(
        pk=1, defaults={"affichage_titre_vide": "sans_titre"}
    )


def reverse_create_default_configuration(apps, schema_editor):
    """Fonction inverse (optionnelle)"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("galeries", "0004_add_configuration_site"),
    ]

    operations = [
        migrations.RunPython(
            create_default_configuration, reverse_create_default_configuration
        ),
    ]
