# Generated by Django 5.2.13 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeries", "0005_create_default_configuration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["ordre_affichage", "nom"],
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="ordre_manuel",
            field=models.BooleanField(
                default=True,
                help_text="Si coché, respecte l'ordre défini par le photographe. Sinon, optimise automatiquement le masonry.",
                verbose_name="Ordre manuel",
            ),
        ),
        migrations.AddField(
            model_name="galerie",
            name="ordre_manuel",
            field=models.BooleanField(
                default=True,
                help_text="Si coché, respecte l'ordre défini par le photographe. Sinon, optimise automatiquement le masonry.",
                verbose_name="Ordre manuel",
            ),
        ),
        migrations.AlterField(
            model_name="photoversion",
            name="traitement",
            field=models.CharField(
                choices=[("couleur", "Couleur"), ("monochrome", "Monochrome")],
                max_length=20,
            ),
        ),
    ]
