# Generated by Django 5.2.13 on 2026-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeries", "0006_alter_collection_options_collection_ordre_manuel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoversion",
            name="taille_fichier_hd",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Taille du fichier haute définition en octets",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photoversion",
            name="taille_fichier_web",
            field=models.PositiveIntegerField(
                blank=True, help_text="Taille du fichier web en octets", null=True
            ),
        ),
    ]
