# Generated by Django 5.2.13 on 2026-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeries", "0007_photoversion_taille_fichier_hd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="cache_mis_a_jour_le",
            field=models.DateTimeField(
                auto_now=True, help_text="Dernière mise à jour du cache de taille"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="taille_totale_cache",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Taille totale en octets (mise à jour automatiquement)",
            ),
        ),
        migrations.AddField(
            model_name="galerie",
            name="cache_mis_a_jour_le",
            field=models.DateTimeField(
                auto_now=True, help_text="Dernière mise à jour du cache de taille"
            ),
        ),
        migrations.AddField(
            model_name="galerie",
            name="taille_totale_cache",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Taille totale en octets (mise à jour automatiquement)",
            ),
        ),
    ]
