# Generated by Django 5.2.13 on 2026-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0008_collection_cache_mis_a_jour_le_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="afficher_details_techniques",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, affiche les métadonnées EXIF (appareil, objectif, réglages) dans les vues de détail des photos.",
                verbose_name="Afficher les détails techniques",
            ),
        ),
        migrations.AddField(
            model_name="galerie",
            name="afficher_details_techniques",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, affiche les métadonnées EXIF (appareil, objectif, réglages) dans les vues de détail des photos.",
                verbose_name="Afficher les détails techniques",
            ),
        ),
    ]
