# Generated by Django 5.2.13 on 2026-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0010_accesgalerie_visiteurgalerie"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsite",
            name="langue",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                help_text="Langue par défaut de l'application",
                max_length=10,
                verbose_name="Langue de l'application",
            ),
        ),
    ]
