# Generated by Django 5.2.13 on 2026-05-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeries", "0011_configurationsite_langue"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsite",
            name="btn_acces_prive",
            field=models.CharField(
                default="Accès privé", max_length=50, verbose_name="Bouton accès privé"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="btn_voir_galeries",
            field=models.CharField(
                default="Voir les galeries",
                max_length=50,
                verbose_name="Bouton galeries",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="description_acces_prive",
            field=models.TextField(
                default="Vous avez reçu un code d'accès pour une galerie privée ? Saisissez-le ci-dessous.",
                verbose_name="Description accès privé",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="description_site",
            field=models.TextField(
                default="Studio photographique : paysages, sport, architecture, documentaire.",
                help_text="Description meta pour les moteurs de recherche",
                verbose_name="Description du site",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="footer_copyright",
            field=models.CharField(
                default="Tous droits réservés",
                max_length=100,
                verbose_name="Texte copyright",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="hero_description",
            field=models.TextField(
                default="Capturer l'instant, révéler l'émotion. Spécialisé dans la photographie de paysages, sport et architecture.",
                help_text="Paragraphe descriptif dans la section hero",
                verbose_name="Description hero",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="hero_sous_titre",
            field=models.CharField(
                default="Studio photographique",
                help_text="Texte au-dessus du titre principal",
                max_length=100,
                verbose_name="Sous-titre hero",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="modal_btn_acceder",
            field=models.CharField(
                default="Accéder à la galerie",
                max_length=50,
                verbose_name="Bouton accès galerie",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="modal_btn_entrer_code",
            field=models.CharField(
                default="Entrer mon code", max_length=50, verbose_name="Bouton modal"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="modal_placeholder_code",
            field=models.CharField(
                default="ABC12345", max_length=50, verbose_name="Placeholder code"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="modal_sous_titre",
            field=models.CharField(
                default="Saisissez votre email et le code reçu pour accéder à la galerie.",
                max_length=200,
                verbose_name="Sous-titre modal",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="modal_titre",
            field=models.CharField(
                default="Accéder à votre galerie",
                max_length=100,
                verbose_name="Titre modal accès",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="msg_mes_galeries",
            field=models.CharField(
                default="Mes galeries", max_length=50, verbose_name="Lien mes galeries"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="msg_mode_prive",
            field=models.CharField(
                default="Mode privé", max_length=50, verbose_name="Badge mode privé"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="msg_quitter_prive",
            field=models.CharField(
                default="Quitter le mode privé",
                max_length=50,
                verbose_name="Tooltip quitter privé",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="msg_sans_titre",
            field=models.CharField(
                default="Sans titre",
                max_length=50,
                verbose_name="Texte photos sans titre",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="nav_acces_prive",
            field=models.CharField(
                default="Accès privé", max_length=50, verbose_name="Menu Accès privé"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="nav_accueil",
            field=models.CharField(
                default="Accueil", max_length=50, verbose_name="Menu Accueil"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="nav_contact",
            field=models.CharField(
                default="Contact", max_length=50, verbose_name="Menu Contact"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="nav_galeries",
            field=models.CharField(
                default="Galeries", max_length=50, verbose_name="Menu Galeries"
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="nom_site",
            field=models.CharField(
                default="Hors les Murs",
                help_text="Nom affiché dans le logo et les titres",
                max_length=100,
                verbose_name="Nom du site",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="titre_acces_prive",
            field=models.CharField(
                default="Accès privé",
                max_length=100,
                verbose_name="Titre section accès privé",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="titre_complet",
            field=models.CharField(
                default="Hors les Murs — Studio Photographique",
                help_text="Titre affiché dans l'onglet du navigateur",
                max_length=200,
                verbose_name="Titre complet",
            ),
        ),
        migrations.AddField(
            model_name="configurationsite",
            name="titre_galeries",
            field=models.CharField(
                default="Galeries",
                max_length=100,
                verbose_name="Titre section galeries",
            ),
        ),
    ]
